INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza bianca con base di mozzarella, speck e noci.', 'Speck e Noci', 8.00, 'https://example.com/images/specknoci.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza con salsiccia fresca e friarielli napoletani.', 'Salsiccia e Friarielli', 8.50, 'https://example.com/images/salsicciafriarielli.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza gourmet con crema di tartufo e funghi porcini.', 'Tartufo e Porcini', 10.00, 'https://example.com/images/tartufoeporcini.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza dolce con Nutella e zucchero a velo.', 'Nutella', 6.00, 'https://example.com/images/nutella.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza con bresaola, rucola e scaglie di grana.', 'Bresaola', 9.00, 'https://example.com/images/bresaola.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza al pesto con pomodorini e mozzarella di bufala.', 'Pesto e Bufala', 8.50, 'https://example.com/images/pestoebufala.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza con salmone affumicato e panna acida.', 'Salmone', 9.50, 'https://example.com/images/salmone.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza al formaggio blu con pere e noci.', 'Gorgonzola e Pere', 9.00, 'https://example.com/images/gorgonzolapere.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza vegetariana con hummus, ceci e verdure grigliate.', 'Vegana', 7.50, 'https://example.com/images/vegana.jpg');
INSERT INTO `pizze` (`descrizione`, `nome_pizza`, `prezzo`, `url_foto`) VALUES ('Pizza con peperoni, cipolla e salsiccia.', 'Rustica', 8.00, 'https://example.com/images/rustica.jpg');
